### ISSUE TITLE
Message am Ende des Offering Prozesses

### ISSUE THREAD

**Issue by ForzaMark** [neighbortrader/FoodBoardApp#71]
Wir schreiben in dem Bericht das wir die Nutzer sensibilisieren wenn sie sich mit fremden treffen. 
Dazu soll eine Nachricht am Ende des Offering Prozesses angezeigt werden.

**Comment by linde9821** [comment]
@ForzaMark meinst du mit 

> Ende des Offering Prozesses

wenn man das erste mal Angebote anzeigen lässt oder wenn man selbst ein Angebot erstellt. Weil im zweiten Fall bin ich mir unsicher was in der Nachricht stehen soll. Kannst du schrieben was du dir da als Message vorstellst?
